### ISSUE TITLE
Feature request: instrument form and all dependencies

### ISSUE THREAD

**Issue by Cyrik** [jpmonettas/hansel#1]
## Problem:
So one of the pain points I always have with instrumentation libraries is that I need to know what to instrument, but I'm using the tool specifically because I don't know the code paths well. Let's say I'm trying to find figure out the flow of a specific function. I now have to tell the tooling what namespaces/functions to instrument, so I just do a big "let's instrument all of it", because I just don't know what's relevant yet. This now means that my traces are filled with data that's not actually relevant to the call I wanted to understand.

## Proposed solution:
`(instrument-form-deeply '(defn foo [bar] (deeper-calls ...))` this would instrument `foo`, but also `deeper-calls` and all the functions it calls and so on. (not of fan of my own naming, so feel free to make it an option in the config or change the function name 😄 ).
This also allows you to instrument, call, uninstrument in one go, so systems where stuff is happening by itself, e.g. server, games and so on, don't trace things not related to the call.
I've got two implementations with finding these dependencies in omni-trace, starting from here https://github.com/Cyrik/omni-trace/blob/977e32b10dd932e3ba0492254e00cfdd1a292e59/src/cyrik/omni_trace/deep_trace.clj#L63

**Comment by jpmonettas** [comment]
Yeah I also think that is a nice functionality have. 

I guess having a function that given a form and a namespace returns all the fn calls inside it is enough, since we can then call instrument recursively.

I'm currently experimenting with something else but I can give it a shot when I find some time!

Thanks again for the idea and your solutions!

**Comment by jpmonettas** [comment]
It is probably tricky for polymorphic fns like multimethods and protocols but following just plain functions is also probably good enough .

**Comment by Cyrik** [comment]
Yeah on stuff where it's not possible to tell I'd include more rather than less but you're right that most of the time it's either normal functions or lambdas.

**Comment by jpmonettas** [comment]
Just implemented an experimental first try on deep var instrumentation. 
Both `hansel.api/instrument-var-clj` and `hansel.api/instrument-var-shadow-cljs` now accept `:deep?` and `:skip-namespaces`.
When `:deep?` is true it will instrument deeply, but automatically skip `clojure.core`, since instrument those will most probably cause issues with the repl itself, tooling, etc.

`:skip-namespaces` is a set that can be used to also prevent the recursive instrumentation to follow some problematic namespaces.
